Repository owncloud/docs-ui, pull requests merged in 2019-11, with the labels that each got.

#73 Update communication links in footer
  src/partials/footer-content.hbs
Labels: cleanup, review required

#97 Add Twitter and OpenGraph meta tags
  src/partials/head-meta-opengraph.hbs
  src/partials/head-meta-twitter.hbs
  src/partials/head-meta.hbs
Labels: enhancement, review required

#46 Added highlighting
  src/scss/main.scss
  src/scss/oc-utilities/oc-highlight.scss
Labels: enhancement
